export const GET_POKEMON_LOADING = "GET_POKEMON_LOADING";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_ERROR = "GET_POKEMON_ERROR";

export const GET_DETAIL_POKEMON_LOADING = "GET_POKEMON_LOADING";
export const GET_DETAIL_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_DETAIL_POKEMON_ERROR = "GET_POKEMON_ERROR";
